services:
  webhook_listener:
    container_name: webhook_listener
    image: ghcr.io/necrolingus/nodejs_webhook_listener_v2:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 3088
    volumes:
      - sqlite_data:/usr/src/app/data
    networks:
        - internal_proxy

networks:
  internal_proxy:
    external: true

volumes:
  sqlite_data: