services:
  webhook_listener:
    image: ghcr.io/necrolingus/nodejs_webhook_listener_v2:latest
    restart: unless-stopped
    env_file: 
      - .env
    expose:
      - 3088
    networks:
        - internal_proxy

  webhook_listener_db:
      image: postgres:17.2-alpine3.21
      restart: unless-stopped
      env_file: 
        - .env
      shm_size: 96mb
      volumes:
        - postgresdata_wl:/var/lib/postgresql/data
      networks:
        - internal_proxy

networks:
  internal_proxy:
    external: true

volumes:
  postgresdata_wl: